#include "pic.h"

void pic_init() {
    out8(PIC_MASTER_COMMAND_REGISTER_PORT, PIC_INIT_WORD);
    out8(PIC_MASTER_DATA_REGISTER_PORT, PIC_MASTER_INTERRUPT_OFFSET);
    out8(PIC_MASTER_DATA_REGISTER_PORT, 1<<PIC_SLAVE_PIN);
    out8(PIC_MASTER_DATA_REGISTER_PORT, PIC_MODE);

    out8(PIC_SLAVE_COMMAND_REGISTER_PORT, PIC_INIT_WORD);
    out8(PIC_SLAVE_DATA_REGISTER_PORT, PIC_SLAVE_INTERRUPT_OFFSET);
    out8(PIC_SLAVE_DATA_REGISTER_PORT, PIC_SLAVE_PIN);
    out8(PIC_SLAVE_DATA_REGISTER_PORT, PIC_MODE);
}

void pic_eoi(int is_slave) {
    if (is_slave) {
        out8(PIC_SLAVE_COMMAND_REGISTER_PORT, PIC_EOI); 
    }
    out8(PIC_MASTER_COMMAND_REGISTER_PORT, PIC_EOI); 
}
